version: '2'

services:
  shop:
    image: 'shop-0.0.1:latest'
    build:
      context: .
    container_name: shop
    depends_on:
      - db2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/price
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - "8080:8080"
  db2:
    image: 'postgres:13.1-alpine'
    container_name: db2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=price
    ports:
      - "5435:5432"